# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"
env:
    - DJANGO="Django==1.8.4"
    - DJANGO="Django==1.9.9"
    - DJANGO="Django==1.10"

# command to install dependencies, e.g. pip install -r requirements.txt
install:
 - pip install $DJANGO
 - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source admin_reorder runtests.py

# report coverage to coveralls.io
after_success: coveralls
